const DEFAULT_FORMSPREE_ENDPOINT =
  process.env.FORMSPREE_VENDOR_ENDPOINT ||
  "https://formspree.io/f/xpqvpzke";

export const DEFAULT_VENDOR_EMAIL =
  "patrick@sentineltechnologygroup.com";

export const SERVICE_PROVIDERS = {
  roofing: {
    serviceLabel: "Roofing",
    providerName: "Default Roofing Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  fencing: {
    serviceLabel: "Fence Services",
    providerName: "Default Fence Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  deck_patio: {
    serviceLabel: "Deck or Patio",
    providerName: "Default Deck and Patio Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  interior_painting: {
    serviceLabel: "Interior Painting",
    providerName: "Default Interior Painting Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  exterior_painting: {
    serviceLabel: "Exterior Painting",
    providerName: "Default Exterior Painting Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  flooring: {
    serviceLabel: "Flooring",
    providerName: "Default Flooring Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  landscaping: {
    serviceLabel: "Landscaping",
    providerName: "Default Landscaping Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  tree_service: {
    serviceLabel: "Tree Service",
    providerName: "Default Tree Service Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  pressure_washing: {
    serviceLabel: "Pressure Washing",
    providerName: "Default Pressure Washing Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  house_cleaning: {
    serviceLabel: "House Cleaning",
    providerName: "Default House Cleaning Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  junk_removal: {
    serviceLabel: "Junk Removal",
    providerName: "Default Junk Removal Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  handyman: {
    serviceLabel: "Handyman Services",
    providerName: "Default Handyman Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  plumbing: {
    serviceLabel: "Plumbing",
    providerName: "Default Plumbing Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  electrical: {
    serviceLabel: "Electrical",
    providerName: "Default Electrical Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  hvac: {
    serviceLabel: "Heating and Air",
    providerName: "Default HVAC Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  foundation: {
    serviceLabel: "Foundation",
    providerName: "Default Foundation Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  pool_service: {
    serviceLabel: "Pool Service",
    providerName: "Default Pool Service Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  home_staging: {
    serviceLabel: "Home Staging",
    providerName: "Default Home Staging Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  moving: {
    serviceLabel: "Moving Services",
    providerName: "Default Moving Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  storage: {
    serviceLabel: "Storage",
    providerName: "Default Storage Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  remodeling: {
    serviceLabel: "General Remodeling",
    providerName: "Default Remodeling Provider",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
  unsure: {
    serviceLabel: "General Home-Service Guidance",
    providerName: "Default Service Coordinator",
    email: DEFAULT_VENDOR_EMAIL,
    formEndpoint: DEFAULT_FORMSPREE_ENDPOINT,
    active: true,
  },
};
